name: Go

on:
  pull_request: {}
  push:
    branches:
      - main

env:
  GO_VERSION: "1.24.1"
  GOLANGCI_VERSION: "v2.0.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: go build -v ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: ${{ env.GOLANGCI_VERSION }}
          args: --timeout=30m --config=.golangci.yml

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1.0.4
        with:
          go-version-input: ${{ env.GO_VERSION }}
          go-package: ./...

  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4.1.6
      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.21.4
        with:
          args: "-no-fail -fmt sarif -out results.sarif ./..."

